language: node_js
node_js: v11.10.0

# S: Build Lifecycle
install:
  - npm install
  # - npm install && npm install gitbook -g && npm install -g gitbook-cli


script:
  - hexo clean && hexo g
  # - bash build_gitbook.sh
  
after_script:
  - bash push_master.sh
# E: Build LifeCycle

branches:
  only:
    - blog_source
env:
 global:
   - GH_REF: github.com/zhongmingmao/zhongmingmao.github.io.git

notifications:
  email:
    recipients:
      - zhongmingmao0625@gmail.com
