language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install
  - npm install gitbook -g
  - npm install -g gitbook-cli

script:
  - hexo clean
  - hexo g

after_script:
  - git clone https://github.com/zhongmingmao/linear-algebra
  - cd linear-algebra
  - gitbook build
  - cp -r _book ../source/linear-algebra
  - cd ..
  - rm -rf linear-algebra
  - cd ./public
  - git init
  - git config user.name "zhongmingmao"
  - git config user.email "zhongmingmao0625@gmail.com"
  - git add .
  - git commit -m "Update Hexo Blog"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog_source
env:
 global:
   - GH_REF: github.com/zhongmingmao/zhongmingmao.github.io.git

notifications:
  email:
    recipients:
      - zhongmingmao0625@gmail.com
